import {describe,it,expect} from "vitest";
import {createProject} from "../lib/music/project";
import {chordCommand,chordGrid,ticksPerBeat,type ChordCommand} from "../lib/music/chord-commands";
import {PPQ,type ChordEvent} from "../lib/music/types";
const fixture=(spans:[string,number,number][])=>{const p=createProject();p.sections[0].lengthTick=8*PPQ;p.chords=spans.map(([id,a,b])=>({id,sectionId:p.sections[0].id,tick:a*PPQ,duration:(b-a)*PPQ,symbol:id,notes:[60,64,67]}));return p;};
const spans=(chords:ChordEvent[])=>chords.sort((a,b)=>a.tick-b.tick).map(c=>[c.id,c.tick/PPQ,(c.tick+c.duration)/PPQ]);
describe("guide timing commands",()=>{
  it("retains translated legacy overlaps and rejects split ID aliasing",()=>{const p=fixture([["C",0,1],["D",3,5],["G",4,6]]);const insert={type:"insert" as const,sectionId:p.sections[0].id,tick:2*PPQ,chord:{...p.chords[0],id:"A",duration:PPQ},remainderId:"split"};const r=chordCommand(p,insert);if(!r.ok)throw Error(r.error);expect(spans(r.document.chords)).toEqual([["C",0,1],["A",2,3],["D",4,6],["G",5,7]]);expect(chordCommand(p,{...insert,tick:PPQ/2,remainderId:"A"}).ok).toBe(false);p.chords[0].tick=-PPQ;expect(chordCommand(p,{type:"replace",sectionId:p.sections[0].id,chordId:"C",symbol:"Custom",notes:[48,60,64]}).ok).toBe(false);});
  it("inserts into a rest, retaining gaps",()=>{const p=fixture([["C",0,2],["D",3,5]]),r=chordCommand(p,{type:"insert",sectionId:p.sections[0].id,tick:2.5*PPQ,chord:{...p.chords[0],id:"G",duration:PPQ},remainderId:"split"});expect(r.ok).toBe(true);if(r.ok){expect(spans(r.document.chords)).toEqual([["C",0,2],["G",2.5,3.5],["D",4,6]]);expect(r.document.tracks).toBe(p.tracks);}});
  it("moves against destination after removing source",()=>{const p=fixture([["A",0,1],["B",2,4],["C",5,6]]),r=chordCommand(p,{type:"move",sectionId:p.sections[0].id,chordId:"A",tick:4*PPQ,remainderId:"split"});if(!r.ok)throw Error(r.error);expect(spans(r.document.chords)).toEqual([["B",1,3],["A",4,5],["C",5,6]]);expect(r.selectedId).toBe("A");});
  it("splits prefix and remainder with supplied identity",()=>{const p=fixture([["C",0,2],["G",2,3]]),r=chordCommand(p,{type:"insert",sectionId:p.sections[0].id,tick:PPQ,chord:{...p.chords[0],id:"Dm",duration:PPQ},remainderId:"remainder"});if(!r.ok)throw Error(r.error);expect(spans(r.document.chords)).toEqual([["C",0,1],["Dm",1,2],["remainder",2,3],["G",3,4]]);});
  it("distinguishes removal and time deletion",()=>{const p=fixture([["C",0,2],["G",3,4]]);for(const [type,tick]of [["remove",3],["deleteTime",1]]as const){const r=chordCommand(p,{type,sectionId:p.sections[0].id,chordId:"C"});if(!r.ok)throw Error(r.error);expect(r.document.chords[0].tick).toBe(tick*PPQ);}});
  it("rejects overflow and locally ambiguous legacy edits without mutation",()=>{const p=fixture([["C",0,4],["G",3,8]]),before=JSON.stringify(p);for(const command of [{type:"resize",sectionId:p.sections[0].id,chordId:"C",duration:5*PPQ},{type:"insert",sectionId:p.sections[0].id,tick:0,chord:{...p.chords[0],id:"D",duration:PPQ},remainderId:"split"}]as ChordCommand[]){expect(chordCommand(p,command).ok).toBe(false);}expect(JSON.stringify(p)).toBe(before);expect(chordCommand(p,{type:"replace",sectionId:p.sections[0].id,chordId:"C",notes:[60,65,69],symbol:"F/C"}).ok).toBe(true);});
  it("uses denominator beats and quarter-beat snaps",()=>{const p=fixture([]);p.timeSignature=[6,8];expect(ticksPerBeat(p)).toBe(480);expect(chordGrid(p,"quarter")).toBe(120);expect(chordGrid(p,"bar")).toBe(2880);});
});
