import {describe,it,expect} from "vitest";
import {createHash} from "node:crypto";
import {createProject,createDemo} from "../lib/music/project";
import {resolveHarmony,progressionNotes} from "../lib/music/harmony";
import {generatePart} from "../lib/music/generate";
import {generatorCases} from "./generator-fixtures";
import baseline from "./generator-baseline.json";
import {PPQ,type NoteEvent} from "../lib/music/types";
const normalize=(notes:NoteEvent[])=>notes.map(({id,...note})=>{void id;return note;});
describe("effective harmony",()=>{
  it("uses minor tonic harmony in minor modes for an empty guide",()=>{const p=createProject();p.key="D";for(const mode of ["minor","dorian","harmonic-minor"] as const){p.mode=mode;const notes=resolveHarmony(p,p.sections[0])[0].notes!;expect(notes.map(n=>n%12)).toEqual([2,5,9]);}});
  it("preserves all 48 ordered baseline outputs and both demos",()=>{for(const c of generatorCases())expect(normalize(generatePart(c.project,c.section,c.options)),c.name).toEqual(baseline.cases.find(b=>b.name===c.name)!.notes);for(const b of baseline.demos){const demo=createDemo(b.reference);for(const [i,t]of demo.tracks.entries())for(const [j,c]of t.clips.entries()){expect(c.notes.length).toBe(b.tracks[i].clips[j].count);expect(createHash("sha256").update(JSON.stringify(normalize(c.notes))).digest("hex")).toBe(b.tracks[i].clips[j].hash);}}});
  it("resumes nested overlaps and uses stored tie order without altering timing",()=>{const p=createProject(),section=p.sections[0];section.lengthTick=4*PPQ;p.chords=[{id:"C",sectionId:section.id,tick:0,duration:4*PPQ,symbol:"C",notes:[60,64,67]},{id:"G",sectionId:section.id,tick:PPQ,duration:PPQ,symbol:"G",notes:[67,71,74]}];const original=JSON.stringify(p.chords);expect(resolveHarmony(p,section).map(s=>[s.startTick/PPQ,s.endTick/PPQ,s.sourceIndex])).toEqual([[0,1,0],[1,2,1],[2,4,0]]);expect(JSON.stringify(p.chords)).toBe(original);p.chords[1].tick=0;p.chords[1].duration=2*PPQ;p.chords[0].duration=PPQ;expect(resolveHarmony(p,section).map(s=>s.sourceIndex)).toEqual([0,1,null]);});
  it("clips crossings using original onsets and differentiates empty guides from gaps",()=>{const p=createProject(),section=p.sections[0];section.startTick=PPQ;section.lengthTick=4*PPQ;p.chords=[{id:"C",sectionId:section.id,tick:0,duration:3*PPQ,symbol:"C",notes:[60,64,67]},{id:"G",sectionId:section.id,tick:PPQ,duration:PPQ,symbol:"G",notes:[67,71,74]}];expect(resolveHarmony(p,section).map(s=>s.sourceIndex)).toEqual([1,0,null]);p.chords=[];expect(resolveHarmony(p,section)[0].notes).not.toBeNull();p.chords=[{id:"outside",sectionId:section.id,tick:9*PPQ,duration:PPQ,symbol:"C",notes:[60,64,67]}];expect(resolveHarmony(p,section)[0].notes).toBeNull();});
  it("generates and auditions the same within-bar harmony with explicit rests",()=>{const p=createProject(),section=p.sections[0];section.startTick=2*PPQ;section.lengthTick=4*PPQ;p.chords=[{id:"C",sectionId:section.id,tick:2*PPQ,duration:PPQ,symbol:"C",notes:[60,64,67]},{id:"D",sectionId:section.id,tick:3*PPQ,duration:PPQ,symbol:"D",notes:[62,66,69]},{id:"F",sectionId:section.id,tick:5*PPQ,duration:PPQ,symbol:"F",notes:[65,69,72]}];for(const role of ["strings","chords","bass","arpeggio","melody"] as const){const notes=generatePart(p,section,{role,energy:.8,density:1,tension:0,register:4,seed:42});if(role!=="bass")expect(notes.some(n=>n.tick>=PPQ&&n.tick<2*PPQ),role).toBe(true);expect(notes.some(n=>n.tick>=2*PPQ&&n.tick<3*PPQ)).toBe(false);expect(notes.every(n=>n.tick<2*PPQ?n.tick+n.duration<=2*PPQ:true)).toBe(true);}expect(progressionNotes(p,section).map(n=>n.tick)).not.toContain(2*PPQ);});
});
