import { test, expect } from "@playwright/test";
import { createProject } from "../../lib/music/project";
import { emptyPatch } from "../../lib/audio/modulation";
import { DEFAULT_CHORD_MOVEMENT } from "../../lib/music/chord-movement";
import { STUDIO_FEATURE_HEADER, STUDIO_MODULATION_FEATURE } from "../../lib/music/performance";

test("updated cloud clients can undo extensions while legacy writes preserve enhanced songs", async ({ page }) => {
  await page.goto("/signin-with-chatgpt?return_to=/");
  await expect(page.getByLabel("Song title")).toBeEnabled();
  const legacy = createProject("Extension compatibility fixture");
  const headers = { Origin: "http://127.0.0.1:5173" };
  const created = await page.request.post("/api/projects", { data: legacy, headers });
  expect(created.status()).toBe(201);
  expect((await page.request.get(`/api/projects/${legacy.id}`)).status()).toBe(200);
  expect((await page.request.get(`/api/projects/${legacy.id}/versions`)).status()).toBe(200);
  const enhanced = structuredClone(legacy);
  enhanced.tracks[0].modulation = emptyPatch();
  enhanced.tracks[0].chordMovement = { ...DEFAULT_CHORD_MOVEMENT, enabled: true };
  const currentHeaders = { ...headers, [STUDIO_FEATURE_HEADER]: STUDIO_MODULATION_FEATURE };
  const saved = await page.request.put(`/api/projects/${legacy.id}`, { data: { document: enhanced, expectedRevision: 1 }, headers: currentHeaders });
  expect(saved.status()).toBe(200);
  const legacyLoad = await page.request.get(`/api/projects/${legacy.id}`);
  expect(legacyLoad.status()).toBe(409);
  expect((await legacyLoad.json()).error).toContain("Reload Chordz");
  const enhancedLoad = await page.request.get(`/api/projects/${legacy.id}`, { headers: currentHeaders });
  expect(enhancedLoad.status()).toBe(200);
  expect((await enhancedLoad.json()).document).toEqual(enhanced);
  const staleWrite = await page.request.put(`/api/projects/${legacy.id}`, { data: { document: enhanced, expectedRevision: 1 }, headers: currentHeaders });
  expect(staleWrite.status()).toBe(409);
  const legacyVersions = await page.request.get(`/api/projects/${legacy.id}/versions`);
  expect(legacyVersions.status()).toBe(409);
  expect((await legacyVersions.json()).error).toContain("Reload Chordz");
  const enhancedVersions = await page.request.get(`/api/projects/${legacy.id}/versions`, { headers: currentHeaders });
  expect(enhancedVersions.status()).toBe(200);
  expect((await enhancedVersions.json())[0].document).toEqual(enhanced);
  const rejected = await page.request.put(`/api/projects/${legacy.id}`, { data: { document: legacy, expectedRevision: 2 }, headers });
  expect(rejected.status()).toBe(409);
  expect((await rejected.json()).error).toContain("Reload Chordz");
  const undone = await page.request.put(`/api/projects/${legacy.id}`, { data: { document: legacy, expectedRevision: 2 }, headers: currentHeaders });
  expect(undone.status()).toBe(200);
  expect((await undone.json()).document).toEqual(legacy);
  const current = await page.request.get(`/api/projects/${legacy.id}`);
  expect(current.status()).toBe(200);
  expect((await current.json()).revision).toBe(3);
  expect((await page.request.delete(`/api/projects/${legacy.id}`, { headers })).status()).toBe(200);
});
